Transition to Cartesi application templates
sunodo/sunodo-templates pull request #39
Opened 2024-04-29 17:33 UTC by tuler

This branch will be the `main` branch of the `cartesi/application-templates` repository.
Not to be merged here

2024-04-29 17:35 UTC, endersonmaia requested changes

2024-04-29 17:35 UTC, endersonmaia commented on README.md
> +Template projects for Cartesi DApps. This repository is used by the Cartesi CLI to create new applications from a specified template project.
```suggestion
Template projects for Cartesi Applications. This repository is used by the Cartesi CLI to create new applications from a specified template project.
```

2024-04-29 17:39 UTC, endersonmaia requested changes

2024-04-29 17:39 UTC, endersonmaia commented on LICENSE
> +Copyright (c) 2023 Cartesi
```suggestion
Copyright (c) 2024 Cartesi
```

2024-04-29 18:12 UTC, endersonmaia approved these changes
Remember to create a branch `0.4-sdk` pointing to main.

Shall we need to create pre-0.4 branches?

2024-04-29 18:16 UTC, tuler commented
> Remember to create a branch `0.4-sdk` pointing to main.

`0.6` right?

> Shall we need to create pre-0.4 branches?

I don't think so.

2024-04-29 18:17 UTC, endersonmaia commented
> > Remember to create a branch `0.4-sdk` pointing to main.
> 
> `0.6` right?
> 
> > Shall we need to create pre-0.4 branches?
> 
> I don't think so.

yes, `0.6-sdk` :man_facepalming:

2024-04-30 16:55 UTC, tuler commented
Pushed to https://github.com/cartesi/application-templates

2024-04-30 16:55 UTC, closed without merging